version: "3"
services:
  react-app:
    build: ./client
    stdin_open: true
    ports: 
      - "3000:3000"
    networks:
      - mern-app
    depends_on:
      - api-server
  api-server:
    build: ./server
    ports:
      - "5000:5000"
    networks:
      - mern-app
networks:
  mern-app:
    driver: bridge