version: '3.8'

services:
  mongodb:
    image: mongo
    container_name: mongo-database
    ports:
      - "27017:27017"
    volumes:
      - db:/data/
    networks:
      - mern-networks
  
  server:
    depends_on:
      - mongodb
    build: ./server
    container_name: node-api
    restart: always
    ports:
      - "5080:5080"
    networks:
      - mern-networks

  client:
    depends_on:
      - server
    build: ./client
    container_name: react-ui
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    networks:
      - mern-networks



networks:
  mern-networks:
    driver: bridge
volumes: 
  db: