version: '3.1'
services:
  db:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mgdata:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    restart: always


  frontend:
    image: 
    build:
      context: .
      ports: 
        - 80:80
    environment:
    depends_on: 
      - backend
    restart: always

  backend:
    image:
    ports:
      - 8080:80
    environment:
    depends_on:
      - db
    restart: always
volumes: